sudo: false
language: node_js
node_js:
  - stable

install:
  - npm install -g codecov
  
script: 
  - npm test
  - codecov
  
after_success:
  - npm run cover
  - bash <(curl -s https://codecov.io/bash)



