# add the following to your codecov.yml
codecov:
  token: 51f1caa5-3b6d-45f4-9cac-21cde6492859
parsers:
  javascript:
    enable_partials: yes
fixes:
  - "before/::after/"  # move path   e.g., "before/path" => "after/path"
  - "::after/"         # move root   e.g., "path/" => "after/path/"
  - "before/::"        # reduce root e.g., "before/path/" => "path/"